### ISSUE TITLE
Territory calculation error in Score and Estimate

### ISSUE THREAD

**Issue by yauwing** [SabakiHQ/Sabaki#662] opened 2020-03-17 18:56 UTC
The attached sgf (zipped to comply with file supported) indicated an error in the Territory score method calculation W+23.5! (White actually resigned. Black should resign if the score was correct) 
Area score method is correct B+ 1.5.
 After checking the Details as in the attached jpg files, it looks like the 12 dead white stones to be removed after end of game were added to wrong side.  (if added to the correct side, it should indicate B+0.5)

There is similar error in Estimate also.

[territorybug.sgf.zip](https://github.com/SabakiHQ/Sabaki/files/4344955/territorybug.sgf.zip)
![Screen Shot 2020-03-17 at 10 53 00 AM](https://user-images.githubusercontent.com/33301926/76887024-db9d4680-683e-11ea-99f8-420b997b2618.jpg)
![Screen Shot 2020-03-17 at 10 52 46 AM](https://user-images.githubusercontent.com/33301926/76887062-e952cc00-683e-11ea-8ca6-97643912783e.jpg)

**Comment by yishn** [comment] 2020-03-17 18:57
This is a duplicate of #658 and is already fixed on master.

**Closed by yishn** 2020-03-17 18:57 UTC
