### ISSUE TITLE
Cannot quit in Mac OS

### ISSUE THREAD

**Issue by Allanware** [SabakiHQ/Sabaki#714] opened 2020-05-07 16:23 UTC
When pressing "cmd + Q" or using the menu to quit the app, it is not actually quitting. The only way to quit this app is to summoning the force quit menu in Mac OS and to force quit it.

**Comment by yishn** [comment] 2020-05-07 17:02
This is a duplicate of #157.

**Closed by yishn** 2020-05-07 17:02 UTC

**Comment by apetresc** [comment] 2026-07-02 15:53
Fixed by #1035 — Sabaki now quits on the first ⌘Q on macOS instead of leaving the process running. (Tracked as a duplicate of #157.)
