### ISSUE TITLE
arm64 build not working on macOS (M1)

### ISSUE THREAD

**Issue by Nibby** [SabakiHQ/Sabaki#879] opened 2022-07-24 05:27 UTC
The macOS arm64 build from [release v0.52](https://github.com/SabakiHQ/Sabaki/releases/tag/v0.52.0) does not run on macOS. I get this error:
<img width="372" alt="Screen Shot 2022-07-24 at 5 21 53 PM" src="https://user-images.githubusercontent.com/1026658/180633586-4af1c161-d3db-459d-80d4-bcfd304dbd64.png">

Some relevant warnings from Console:
```
error	17:22:04.143373+1200	Finder	LAUNCH: Failure de.yichuanshen.sabaki <private> should not be translocated.
error	17:22:04.143390+1200	Finder	LAUNCH:translocate failed, de.yichuanshen.sabaki <private>, error=Error Domain=NSPOSIXErrorDomain Code=16 "Resource busy"
error	17:22:04.143409+1200	Finder	LAUNCH: Launch failure with -47/fBsyErr <private>
error	17:22:04.143769+1200	CoreServicesUIAgent	handle LS launch error: {\n    Action = oapp;\n    AppMimimumSystemVersion = "11.0";\n    AppPath = "/Users/nibby/Downloads/Sabaki.app";\n    ErrorCode = "-47";\n}
```

Tested on a Mac Studio with M1 Max chip.

**Comment by yangli-stat** [comment] 2022-07-31 11:46
Me too. It says the app has been damaged and can't be run on M1 MacBook Pro.

**Comment by apetresc** [comment] 2022-08-01 21:11
This is almost certainly a duplicate of #817 - there are several workarounds described there. I definitely need to update the README with instructions about this, thank you for the reminder :)

**Closed by apetresc** 2022-08-01 21:11 UTC
