### ISSUE TITLE
Game Manager Enhancements

### ISSUE THREAD

**Issue by jufis** [SabakiHQ/Sabaki#757] opened 2020-12-03 11:34 UTC
Game Manager needs to be extended to support:

1) support list mode (with detailed columns for each of the metadata available on an SGF). Now every single game occupies too much space.
2) I want to be able to load/import zip file with thousand of games ie. support compressed sgf format
3) Allow to search through all metadata of the games. Ie. find castle games or a specific player.
4) A players pane would be nice to allow to find your favourite player and select each game for viewing/analysis afterwards.
5) Performance: I tried importing all the GoGoD db and the app froze resulting on a black screen in game manager.

Version tested 0.51.0

**Comment by yishn** [comment] 2020-12-03 16:18
1. is duplicate of #146 
2. Simply extract the zip yourself and add the files. You can add multiple files at once.
3. The filter input field should search through relevant metadata of the games, which should include game name and player names.
4. See below.
5. Since the game manager of Sabaki manages all games within a single SGF file, Sabaki needs to hold all games in memory at once, unlike an actual database which can index a large amount of games and load the game you want only. I recommend managing separate games in separate files, maybe include up to 10 games in a series (e.g. a series of games between two players during an event) in one file.

Since Sabaki has no ambition to provide a database, i.e. the Sabaki game manager is designed to (and also only need to) handle a small amount of games, I don't really see the benefit to provide extensive filter and grouping tools.

**Closed** 2021-04-06 15:19 UTC
