### ISSUE TITLE
The last point mark in the theme is too big.

### ISSUE THREAD

**Issue by leech8902** [SabakiHQ/Sabaki#957] opened 2024-05-07 10:26 UTC
/
![캡처](https://github.com/SabakiHQ/Sabaki/assets/169149672/07b26b2a-57b1-4776-af30-31d4c342deec)

I installed it under the Baduktv theme and everything else is good but it's inconvenient because the last starting point is too big.

**Comment by HackYardo** [comment] 2024-09-18 01:20
That's what the **Baduktv** theme does, I just tried.

**Comment by apetresc** [comment] 2024-09-24 17:33
This is a duplicate of #938. It's a consequence of a change to Sabaki's DOM that the theme needs to update to account for. The solution is here: https://github.com/upsided/Upsided-Sabaki-Themes/issues/1 I'm still hoping @upsided will one day implement my fix :( I know those themes are very popular.

**Closed by apetresc** 2024-09-24 17:33 UTC
