### ISSUE TITLE
KataGo compatibility issue (unable to change komi)

### ISSUE THREAD

**Issue by kennyjin** [SabakiHQ/Sabaki#590] opened 2019-06-27 00:24 UTC
KataGo supports different komi value than 7.5. However, when using Sabaki to load KataGo (and analyze games), it seems that the komi value will be automatically overwritten (to 7.5). See below:
![image](https://user-images.githubusercontent.com/20588677/60224409-d713a680-9847-11e9-87d1-fc5608a5f9dd.png)

**Comment by yishn** [comment] 2019-08-06 07:27
Anyone else can reproduce this?

**Comment by Nihisil** [comment] 2019-10-29 09:10
I can't reproduce it as well.

![image](https://user-images.githubusercontent.com/475367/67752925-da75a380-fa6e-11e9-9fc7-62a65b4f18f1.png)

Ubuntu, Katago v1.2, Sabaki v0.43.3

**Comment by yishn** [comment] 2019-10-29 10:58
I will close this issue then.

**Closed by yishn** 2019-10-29 10:58 UTC
Labels: help wanted
