### ISSUE TITLE
Auto play hangs when using Leela Zero in Analysis mode

### ISSUE THREAD

**Issue by larspensjo** [SabakiHQ/Sabaki#545] opened 2019-04-07 19:29 UTC
1. Configure game engines to use Leela Zero for both black and white. Use the following flags:
-g --noponder -t 8 --randomcnt 10 --lagbuffer 0
Use the command
time_settings 0 10 1
2. Attach the same engine to black and white.
3. Toggle Analysis (F4)
4. Start self-play (F5)

After some moves (at about 40 on average), the progress will stop. Usually, the "analysis result" will continue, but no new moves will be generated.

Running on Windows 10. The problem seems to be independent of using LZ 0.16 or 0.17, and independent of network version.

The picture shows an example of a stuck game. The "busy wheels", marked in red, are both turning, but no playouts are shown.

![image](https://user-images.githubusercontent.com/2412342/55688695-aecc8800-597b-11e9-8b92-91cc5efb2a57.png)

**Comment by fohristiwhirl** [comment] 2019-04-07 20:33
I was able to reproduce this. Pressing escape didn't let me get out of it, either.

**Comment by yishn** [comment] 2019-04-07 22:29
Does this also happen when you're not in analysis mode? Maybe also try enabling GTP logging and send us the logs.

**Comment by fohristiwhirl** [comment] 2019-04-07 23:59
This is a wild hunch based on my own experiences, but is 100% of the stderr *from both engines* being consumed? I've seen LZ hang if this isn't so.

**Comment by yishn** [comment] 2019-04-08 06:01
@fohristiwhirl What do you mean by 'consuming' stderr 100%? We do show stderr from both engines.

**Comment by larspensjo** [comment] 2019-04-08 06:35
It has never happened to me if Analysis mode is disabled.

**Comment by larspensjo** [comment] 2019-04-08 07:58
The stderr thing is an interesting hypothesis. If that channel isn't consumed, the sending process will eventually block, won't it?

That is just the way it behaves. That is, it seems to always block, but not at the same place. It seems to be inevitable.

**Comment by fohristiwhirl** [comment] 2019-04-08 14:49
> What do you mean by 'consuming' stderr 100%? We do show stderr from both engines.

It was just a stab in the dark based on something that's happened to me several times in my own projects. Yes, basically if Sabaki were to fall behind on reading stderr, eventually LZ wouldn't be able to write any more because the buffer / pipe is full. But it sounds like this can't be the problem.

**Comment by dbosst** [comment] 2019-04-12 21:47
Not 100% sure if it's the same bug, but it if happens ONLY in analysis mode it should be fixed in LZ 0.17, as it might be related to [this leela-zero bug that was patched in 0.17](https://github.com/leela-zero/leela-zero/issues/2001) (where the info move line wasn't getting printed if there is not enough time).

Are you sure you can reproduce it with LZ 0.17 or when its not in analysis mode? Turn on the debugger console (see if there are any errors) and especially enable GTP logging and provide a log so we can check its not a leela=zero bug.

FYI: I've seen leela-zero return no move on occasion when the time left for a move was 0 or extremely short, but its hard to reproduce and track down (I haven't gotten around to reporting it yet).

**Comment by larspensjo** [comment] 2019-04-12 22:11
It only happens with analysis mode. But it happens for both LZ 0.16 and 0.17. It never happens if I do not use the analysis mode. It is very easy to repeat as it happens 100%. But the number of needed moves varies, usually it hangs at move 27-29.

How do I turn on the debugger Sabaki console?

See the two attached log files. One from the 40b network, and one from the 15b network. This time, the last played move was number 29 by black (the 40b network).

[15b-log.txt](https://github.com/SabakiHQ/Sabaki/files/3075312/15b-log.txt)
[40b-log.txt](https://github.com/SabakiHQ/Sabaki/files/3075313/40b-log.txt)

**Comment by larspensjo** [comment] 2019-04-12 22:15
If I kill the game, force-save it, restart Sabaki, load the saved game, re-attaches LZ networks, starts the analysis mode and starts the autoplay again (F5), the game will play another 28 moves or so until it hangs again.

**Comment by dbosst** [comment] 2019-04-12 23:16
> It only happens with analysis mode. But it happens for both LZ 0.16 and 0.17. It never happens if I do not use the analysis mode. It is very easy to repeat as it happens 100%. But the number of needed moves varies, usually it hangs at move 27-29.
> 
> How do I turn on the debugger Sabaki console?
> 
> See the two attached log files. One from the 40b network, and one from the 15b network. This time, the last played move was number 29 by black (the 40b network).
> 
> [15b-log.txt](https://github.com/SabakiHQ/Sabaki/files/3075312/15b-log.txt)
> [40b-log.txt](https://github.com/SabakiHQ/Sabaki/files/3075313/40b-log.txt)

If you look at the logs LZ sends the search results but doesn't send a "play" command, it looks like a LZ problem not a Sabaki problem, but I think I would need to debug the LZ code to be absolutely sure Sabaki isn't closing the pipe prematurely. I will take a look into this if I can try to reproduce it tomorrow.

**Comment by larspensjo** [comment] 2019-04-13 07:06
Thank you!

**Comment by dbosst** [comment] 2019-04-13 13:06
I was finally able to reproduce it again, and looking at your log and mine and saw something obvious that I overlooked.  When two engines are playing each other with analysis enabled, Sabaki seems to be sending both a lz-genmove_analyze to one engine and simultaneously a lz-analyze to the other engine (the second of which shouldn't happen).

**Closed** 2019-04-13 13:46 UTC
Labels: bug, help wanted, more info needed

**Comment by yishn** [comment] 2019-04-13 13:50
I suspect that this comes from Sabaki sending the `analyze` command to both engines at once. I've fixed this with this commit. @dbosst, @larspensjo Can you see if this issue still persists with this new fix?

**Comment by dbosst** [comment] 2019-04-13 13:54
Doh I just figured that out and fixed it myself ;)

**Comment by larspensjo** [comment] 2019-04-13 14:06
@yishn Sorry, I don't have the development environment, so I can't test.

Anyway, thanks for the support and an excellent application!
