### ISSUE TITLE
windows defender found threat in sabaki 0.50

### ISSUE THREAD

**Issue by ncdlek** [SabakiHQ/Sabaki#642] opened 2020-03-11 19:43 UTC
![image](https://user-images.githubusercontent.com/1558402/76457359-b7c6a480-63e9-11ea-8a38-320b828b6cd8.png)

https://www.microsoft.com/en-us/wdsi/threats/malware-encyclopedia-description?name=Trojan%3aWin32%2fBulta!rfn&threatid=2147694403

**Comment by yishn** [comment] 2020-03-11 20:17
Duplicate of #641.

**Closed by yishn** 2020-03-11 20:17 UTC
